/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/changelog': RouteRecordInfo<
      '/changelog',
      '/changelog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/': RouteRecordInfo<
      '/legal/',
      '/legal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/cookies': RouteRecordInfo<
      '/legal/cookies',
      '/legal/cookies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/disclaimer': RouteRecordInfo<
      '/legal/disclaimer',
      '/legal/disclaimer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/imprint': RouteRecordInfo<
      '/legal/imprint',
      '/legal/imprint',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/opt-out': RouteRecordInfo<
      '/legal/opt-out',
      '/legal/opt-out',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/privacy': RouteRecordInfo<
      '/legal/privacy',
      '/legal/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/terms': RouteRecordInfo<
      '/legal/terms',
      '/legal/terms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/changelog.vue': {
      routes:
        | '/changelog'
      views:
        | never
    }
    'src/pages/legal/index.vue': {
      routes:
        | '/legal/'
      views:
        | never
    }
    'src/pages/legal/cookies.vue': {
      routes:
        | '/legal/cookies'
      views:
        | never
    }
    'src/pages/legal/disclaimer.vue': {
      routes:
        | '/legal/disclaimer'
      views:
        | never
    }
    'src/pages/legal/imprint.vue': {
      routes:
        | '/legal/imprint'
      views:
        | never
    }
    'src/pages/legal/opt-out.vue': {
      routes:
        | '/legal/opt-out'
      views:
        | never
    }
    'src/pages/legal/privacy.vue': {
      routes:
        | '/legal/privacy'
      views:
        | never
    }
    'src/pages/legal/terms.vue': {
      routes:
        | '/legal/terms'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
